[package]
name = "db-types"
version = "0.1.0"
edition.workspace = true

[dependencies]
diesel = { version = "2", features = ["postgres", "chrono", "numeric"] }
serde = { version = "1", features = ["derive"] }
chrono = { version = "0.4", features = ["serde"] }
bigdecimal = { version = "0.4", features = ["serde"] }
validator = { version = "0.18", features = ["derive"] }
